### ISSUE TITLE
Can not start memcached

### ISSUE THREAD

**Issue by edurenye** [lando/lando#1803]
I purged all docker images and containers and then I started my lando app that contains the memcached service:

`
cache:
    type: memcached
`
Nothing fancy on it, and then I got:

> ERROR: No container found for cache_1
error: Looks like cache is not running! It should be so this is a problem.
warn: Try running `lando logs -s cache` to help locate the problem!

I did `lando logs -s cache`
And I got:

> cache_1      | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
cache_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
cache_1      | Running command /app-entrypoint.sh /run.sh
cache_1      | Running with exec!
cache_1      | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
cache_1      | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
cache_1      | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
cache_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
cache_1      | Running command /app-entrypoint.sh /run.sh
cache_1      | Running with exec!
cache_1      | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found

My guess is that memcached had changed something in the last version and it does not work anymore, I worked arround it using `type: memcached:1.5.12`
With that tag it worked.

**Comment by marcaddeo** [comment]
I'm experiencing this as well

**Comment by iBobik** [comment]
Something similar:

```
Starting tvs_cache_1 ... done
ERROR: No container found for cache_1
error: Looks like cache is not running! It should be so this is a problem.
warn: Try running `lando logs -s cache` to help locate the problem!
```
```
Attaching to tvs_cache_1
cache_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
cache_1      | Running command /app-entrypoint.sh /run.sh
cache_1      | Running with exec!
cache_1      | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
cache_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
cache_1      | Running command /app-entrypoint.sh /run.sh
cache_1      | Running with exec!
cache_1      | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
```

**Comment by wk-rasel** [comment]
I am having the same problem.

**Comment by SaraKlasson** [comment]
Same problem.

**Comment by johangant** [comment]
Confirmed, experienced this earlier today. Tag fix from https://github.com/lando/lando/issues/1803#issue-498778980 did work, possibly an upstream issue?

**Comment by wk-rasel** [comment]
Hi @edurenye I had the problem few hours ago now its fixed.

Steps I did:
- Uninstalled lando and docker.
- Installed again lando rc20 (It will install docker version 2.1.0.1, DONT update docker to the latest)
- lando start

**Comment by iBobik** [comment]
Downgrading from Docker 2.1.0.3 to 2.1.0.1 _solved_ the problem.

If you use brew then the downgrade can be done easilly by this:
```
brew cask reinstall https://raw.githubusercontent.com/Homebrew/homebrew-cask/5037705e8ed028ae1a45c6fb7d6b94e5fb0cc8d8/Casks/docker.rb
```

But I would not close the issue because solution should be to support current Docker.

**Comment by asaphko** [comment]
Having a very similar issue with a (relatively) simple .lando.yml setup:

`name: csms-express
recipe: mean
config:
  node: 10
  build:
    - npm install

  command: npm start
  database: mongo:4.0
  globals: []
  port: '3000'
  ssl: false
  config:
    database: mongo
`

That results in:

`database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /app-entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
database_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1   | Running command /app-entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found`

Downgrading to Docker Desktop to 2.1.0.1 and Lando to 3.0.0-rc19 does not resolve the problem.

**Comment by pirog** [comment]
AFAIK this was fixed in https://github.com/lando/lando/releases/tag/v3.0.0-rc.21

**Comment by nathandentzau** [comment]
This is not fixed. Experiencing this on Ubuntu 19.10 using v3.0.0-rc.22 on Docker Docker version 19.03.3, build a872fc2f86:

```
memcached_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
memcached_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
memcached_1   | mkdir: cannot create directory '/etc/ssh': Permission denied
memcached_1   | chmod: changing permissions of '/launch.sh': Operation not permitted
memcached_1   | Running command /bin/sh -c chmod +x /launch.sh && /launch.sh
```

**Comment by iBobik** [comment]
I use v3.0.0-rc.22 and Memcached works. Did you tried to rebuild stack?

**Comment by edwardcrompton** [comment]
I get the error described by @nathandentzau using Docker version 19.03.4, Lando v3.0.0-rc.22 and Ubuntu 16.04 LTS.

I've tried forcing the memcached version to 1.5.12 as described in https://github.com/lando/lando/issues/1803#issue-498778980 and doing a `lando rebuild` but to no avail.

**Comment by trepmag** [comment]
Reproducing with Lando v3.0.0-rc.23 here and tried also with memcached:1.5.12; same logs as in https://github.com/lando/lando/issues/1803#issuecomment-553174779

**Comment by edwardcrompton** [comment]
Looks as though we should reopen this @pirog?

**Comment by tormi** [comment]
Let's continue here maybe: https://github.com/lando/lando/issues/1827#issuecomment-571979571

**Comment by pirog** [comment]
good call @tormi, closing in favor of #1827
