### ISSUE TITLE
NET::ERR_CERT_INVALID on Chrome

### ISSUE THREAD

**Issue by richcollins** [lando/lando#1831]
lando version: v3.0.0-rc.22
os: macOS 10.15 (19A583)
browser: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

When I access https://mysite.lndo.site, I get the error:

NET::ERR_CERT_INVALID

**Comment by Puremugleblood** [comment]
bumping, having the same issue

**Comment by ralphvandenhoudt** [comment]
bumping, having the same issue

**Comment by sryanb** [comment]
Bump. Fine in other browsers, have done full reset of Chrome settings, full re-install etc.

**Comment by sryanb** [comment]
I was able to solve this by running `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/.lando/certs/lndo.site.pem`

**Comment by ericstroo** [comment]
> I was able to solve this by running
> `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/.lando/certs/lndo.site.pem`

I'm not able to replicate that fix but am able to replicate the issue since upgrading to Catalina.

**Comment by ericstroo** [comment]
I was able to resolve locally by removing all references lndo.site from my keychain and then rebuilding my lando containers.

**Comment by jagwire16** [comment]
I confirm that I am receiving the error as well.

OS: macOS Catalina 10.15.1 (19B88)
Browser: Chrome Version 78.0.3904.87 (Official Build) (64-bit)

Site: https://podcast.redacted.com.lndo.site (`*.*.*.lndo.site`)

Error: NET::ERR_CERT_INVALID

I did verify that the certificate has `*.*.*.lndo.site` as a SAN.

I also verified that, in Safari, I could add an exception for the untrusted cert and browse the site successfully.

**Comment by ralphvandenhoudt** [comment]
I solved the issue by updating Lando to the lastest version. The update of MacOS to Catalina seemed to be the problem.

**Comment by RyanBaron** [comment]
> I was able to solve this by running
> `sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain ~/.lando/certs/lndo.site.pem`

@sryanb thanks!, this worked for me as well. (macOS 10.15.1)

**Comment by pirog** [comment]
This should be resolved in rc.22/23. Note that resolving this error is not the same as whitelisting your CA which is documented here: https://docs.lando.dev/config/global.html

**Comment by daliborstojakovic** [comment]
Same issue still on linux. Tested on Ubuntu 19.10 and on lando rc23. Same issue happens. Tried to add certificates like documented here: https://docs.lando.dev/config/security.html#trusting-the-ca but regardless site shows as not secure on Chrome.

**Comment by brooke-heaton** [comment]
I have followed the instructions above for Linux and it is not working. Still showing Not secure on chrome.

**Comment by bronius-congruity** [comment]
Very old issue here, but I went around and around. Finally (based on what caused it for me -- having deleted `~/.lando` during some over-zealous troubleshooting) what worked was:
- Delete lando certs from keychain (search "lando" in Keychain Access, delete)
- Rebuild your lando site(s) which will also detect missing and rebuild lando CA cert
- **Restart Chrome** (or whatever browser(s)) and try visiting the site again
hth
