### ISSUE TITLE
bitnami/mysql updated entrypoints

### ISSUE THREAD

**Issue by gtjamesa** [lando/lando#2057]
I encountered the following earlier, after rebuilding my application:

```bash
database_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1      | /lando-entrypoint.sh: 26: exec: /entrypoint.sh: not found
database_1      | Running command /entrypoint.sh /run.sh
database_1      | Running with exec!
database_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1      | Running command /entrypoint.sh /run.sh
database_1      | Running with exec!
database_1      | /lando-entrypoint.sh: 26: exec: /entrypoint.sh: not found
database_1      | mkdir: cannot create directory '/etc/ssh': Permission denied
database_1      | Running command /entrypoint.sh /run.sh
database_1      | Running with exec!
database_1      | /lando-entrypoint.sh: 26: exec: /entrypoint.sh: not found
```

I took a look around, and [bitnami has updated the paths of their `entrypoint.sh` and `run.sh` scripts](https://github.com/bitnami/bitnami-docker-mysql/commit/f954caf58bc443b134407d50c6dcec10e8f80aff). They are now located at:

* `/opt/bitnami/scripts/mysql/entrypoint.sh`
* `/opt/bitnami/scripts/mysql/run.sh`

While debugging I destroyed my application to see if that was the issue (it wasn't) but managed to get my database container running by overriding the default command. Hopefully, this helps someone. I will submit a PR in the morning if it hasn't already been done.

```yaml
services:
  database:
    overrides:
      command: /lando-entrypoint.sh /opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh
```

**Comment by dustinleblanc** [comment]
Thanks @gtjamesa! We're going to hotfix this ASAP, in the meantime, here is another solution: https://github.com/lando/lando/pull/2058

**Comment by gtjamesa** [comment]
Thanks for the fast reply @dustinleblanc. Ah great, I've now locked the version in my Landofile to `bitnami/mysql:5.7.28`

**Comment by timothyjensen** [comment]
Thanks @gtjamesa. Changing `database: mysql:5.7` to `database: mysql:5.7.28` worked for me.

**Comment by Farnoosh63** [comment]
@timothyjensen Thanks for the quick fix. It worked for me.

**Comment by pirog** [comment]
Alright this should be fixed in the next release which is about to drop!

**Comment by fede-green** [comment]
Hi guys, 

i have a very similar problem still on **v3.0.0-aft.2** and using 

```
services:
  database:
    type: mariadb:10.2```

I tried the workaroung mentioned in the first comment, but no luck... do you have any suggestion? How can i see what's the image in use?

Thanks for the help!

**Comment by rabauss** [comment]
You have to try `mariadb:10.2.31-debian-10-r47` but I think this is not allowed with `< aft.2`.
Please try `rrc.1`!

**Comment by fede-green** [comment]
thanks, will try downgrading both then! now i randomly picked `10.2.31` and i'm trying it on `aft.2`... let's see! Will post the result :)

**Comment by fede-green** [comment]
mhm... neither `type: mariadb:10.2.31-debian-10-r47` on `rrc.1` seems to work :( :

```Running command /lando-entrypoint.sh /opt/bitnami/scripts/mysql/entrypoint.sh /opt/bitnami/scripts/mysql/run.sh
database_1    | Running with exec!
```

**Comment by rabauss** [comment]
But I think in rrc.1 this should not be neccessary - because it's pinned from lando - see: 
https://github.com/lando/lando/blob/55efb0e02ec5282251728a996e93e410fdea4e7c/plugins/lando-services/services/mariadb/builder.js#L15

**Comment by pirog** [comment]
Exactly. In rrc1 you should not have to pin directly. You will however have
to do a rebuild to reset the image tags though
