### ISSUE TITLE
Issue with drush not installing on initial build of drupal 7 recipe

### ISSUE THREAD

**Issue by featherbelly** [lando/lando#2079]
**Tell us about your setup**

Lando version v3.0.0-aft.2 on Mac OSX 10.15.3

**Tell us about your `.lando.yml`**

```
name: amg-ate
recipe: drupal7
config:
  php: '7.2'
  via: nginx
  webroot: web
  database: postgres:9.6
  xdebug: false
services:
  database:
    portforward: 5434
  node:
    type: node
    build:
      - yarn
  cache:
    type: redis
    persist: true
  accelerator:
    type: varnish
    backends:
      - appserver_nginx
  search:
    type: elasticsearch:6
tooling:
  gulp-start:
    service: node
    description: Runs yarn DEV commands in theme
    cmd:
      - sh -c 'cd /app/web/sites/all/themes/AMG && yarn install && yarn run start'
  gulp-build:
    service: node
    description: Runs yarn BUILD commands in theme
    cmd:
      - sh -c 'cd /app/web/sites/all/themes/AMG && yarn install && yarn run build'
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

```lando drush```

**Tell us about the error you got**

```lando drush
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown```

```lando drush -vvv
info: Bootstraping...
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","TERM":"xterm","LANDO_HOST_UID":"501","LANDO_HOST_GID":"20","LANDO_HOST_USER":"featherbelly","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"/Users/featherbelly/.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"/Users/featherbelly","LANDO_HOST_OS":"darwin","LANDO_HOST_IP":"host.docker.internal","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"229c08fec066b5043bb6f581f124f4b2d63d1ade"},"gid":"20","uid":"501","username":"featherbelly","caCert":"/Users/featherbelly/.lando/certs/lndo.site.pem","caDomain":"lndo.site","caKey":"/Users/featherbelly/.lando/certs/lndo.site.key","caProject":"landocasetupkenobi38ahsoka229c08fec066b5043bb6f581f124f4b2d63d1ade"}}
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
debug: Plugin lando-events has undefined
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
debug: Plugin lando-networking has {"config":{"networkBridge":"lando_bridge_network"}}
verbose: Plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js
debug: Plugin lando-pantheon has undefined
verbose: Loading event post-bootstrap-config priority 5
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
debug: Plugin lando-proxy has {"config":{"proxy":"ON","proxyCert":"/certs/cert.crt","proxyKey":"/certs/cert.key","proxyName":"landoproxyhyperion5000gandalfedition","proxyDash":"58087","proxyCache":"proxyCache","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyDomain":"lndo.site","proxyIp":"127.0.0.1"}}
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
debug: Plugin lando-recipes has undefined
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
debug: Plugin lando-services has undefined
verbose: Plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js
debug: Plugin lando-sharing has undefined
verbose: Plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
debug: Plugin lando-test has {"plugin-test":true}
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
debug: Plugin lando-tooling has undefined
debug: Emitting event post-bootstrap-config
debug: Event post-bootstrap-config has 1 listeners
info: config bootstrap completed.
info: tasks bootstrap beginning...
debug: Emitting event pre-bootstrap-tasks
debug: Event pre-bootstrap-tasks has 0 listeners
debug: Autoloaded task config
debug: Autoloaded task destroy
debug: Autoloaded task info
debug: Autoloaded task list
debug: Autoloaded task logs
debug: Autoloaded task poweroff
debug: Autoloaded task rebuild
debug: Autoloaded task restart
debug: Autoloaded task share
debug: Autoloaded task start
debug: Autoloaded task stop
debug: Autoloaded task version
debug: Autoloaded task init
debug: Autoloaded task ssh
debug: Emitting event post-bootstrap-tasks
debug: Event post-bootstrap-tasks has 0 listeners
info: tasks bootstrap completed.
info: engine bootstrap beginning...
debug: Emitting event pre-bootstrap-engine
debug: Event pre-bootstrap-engine has 0 listeners
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /Users/featherbelly/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /Users/featherbelly/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /Users/featherbelly/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /Users/featherbelly/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /Users/featherbelly/.lando/scripts and setting 755
debug: Emitting event post-bootstrap-engine
debug: Event post-bootstrap-engine has 0 listeners
info: engine bootstrap completed.
info: Bootstrap completed.
debug: Emitting event cli-answers
debug: Event cli-answers has 0 listeners
debug: Emitting event cli-drush-answers
debug: Event cli-drush-answers has 0 listeners
debug: Emitting event cli-run
debug: Event cli-run has 0 listeners
debug: Emitting event cli-drush-run
debug: Event cli-drush-run has 0 listeners
debug: Emitting event pre-drush
debug: Event pre-drush has 0 listeners
verbose: Running pid1 ["/Applications/Docker.app/Contents/Resources/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","amgate_appserver_1","drush","-vvv"] in PATH with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":["inherit","inherit","ignore"]}, mode=attach, detached=false, cwd=PATH
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown
verbose: [
  '/Applications/Docker.app/Contents/Resources/bin/docker',
  'exec',
  '--tty',
  '--interactive',
  '--user',
  'www-data',
  '--workdir',
  '/app',
  '--env',
  'PHP_MEMORY_LIMIT=-1',
  'amgate_appserver_1',
  'drush',
  '-vvv'
] finished with code 126
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-isRunning
debug: Event pre-engine-isRunning has 0 listeners
debug: Emitting event post-engine-isRunning
debug: Event post-engine-isRunning has 0 listeners
debug: Logging metrics data {"command":"lando drush","context":"local","devMode":false,"instance":"229c08fec066b5043bb6f581f124f4b2d63d1ade","nodeVersion":"v12.13.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"19.3.0","arch":"x64"},"product":"lando","version":"3.0.0-aft.2","message":"","stack":"Error\n    at /snapshot/lando/build/cli/lib/shell.js\nFrom previous event:\n    at Shell.sh (shell.js)\n    at Object.dockerExec (utils.js)\n    at /snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js\nFrom previous event:\n    at Object.run (build.js)\n    at /snapshot/lando/build/cli/lib/bootstrap.js\n    at /snapshot/lando/build/cli/lib/cli.js\nFrom previous event:\n    at Object.handler (cli.js)\n    at Object.runCommand (command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)\n    at Function.get [as argv] (yargs.js:1004:21)\n    at Cli.init (cli.js)\n    at Cli.run (cli.js)\n    at Object.<anonymous> (lando.js)\n    at Module._compile (bootstrap.js:1324:22)\n    at Function.Module.runMain (bootstrap.js:1379:12)\n    at internal/main/run_main_module.js:17:11","action":"error","created":"2020-03-21T17:20:57.445Z"} to [{"report":true,"url":"https://metrics.lando.dev"}]
```

**Tell us generally about your bug**

After a fresh install of the new Lando version and a rebuild of all containers I get the above error when trying to run `lando drush`. I have tried destroying and removing all containers, images, and volumes and doing a rebuild and same problem. 

If I drop into the container `lando ssh` and try running drush I get `bash: drush: command not found`. 

If I run `lando rebuild -y` then drush is available...

**Comment by pirog** [comment]
@featherbelly this can happen if you remove your apps containers manually (eg through a docker reset or uninstall) and then try to start up a lando app again. Lando will set a build cache file to let itself know that a build vs a normal start is required. This file is removed on a lando destroy. 

Perhaps we could add a deeper check to handle cases like this so the build cache file is destroyed if you try to start an app without any containers existing.

**Comment by featherbelly** [comment]
Thanks Mike. Initially I just upgraded Lando and then ran  `lando rebuild -y` and it seemed drush was missing. So I tried removing all containers (it was time for a cleanup anyway) as mentioned above.

**Comment by pirog** [comment]
Hmm interesting. I'll test that out but usually the `rebuild` will kick off the build process again. Are you sure you didn't `lando restart` instead?

**Comment by pirog** [comment]
OK this should be fixed in the next release!

**Comment by arcataroger** [comment]
As per #1542 , this is still happening :(

Windows 10 (10.0.18363.836) with Lando 3.0.4 & the Pantheon recipe. Failed on the very first `lando start`.

A `lando rebuild` resulted in a
```
ERROR: No container found for nodejs_1
ERROR ==>  message=, stack=Error
    at C:\snapshot\lando\build\cli\lib\shell.js

[snip]

 ██████╗██████╗  █████╗ ███████╗██╗  ██╗██╗██╗██╗
██╔════╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██║██║
██║     ██████╔╝███████║███████╗███████║██║██║██║
██║     ██╔══██╗██╔══██║╚════██║██╔══██║╚═╝╚═╝╚═╝
╚██████╗██║  ██║██║  ██║███████║██║  ██║██╗██╗██╗
 ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝╚═╝
```

A `lando stop` and `lando destroy` and `lando start` again resulted in:
```

ERROR: No container found for nodejs_1
ERROR ==>  message=, stack=Error
    at C:\snapshot\lando\build\cli\lib\shell.js

[snip]

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
```

**Comment by pirog** [comment]
@arcataroger this is likely because your `nodejs` is not configured correctly. provide steps to replicate and we will look into it.
