### ISSUE TITLE
"Lando Pull" — error pulling database "ERROR 1064 (42000) at line 1:"

### ISSUE THREAD

**Issue by RayHollister** [lando/lando#2478]
**Tell us about your setup**

lando v3.0.7 OSX 10.15.5

**Tell us about your `.lando.yml`**

```yml
name: wjct
recipe: pantheon
config:
  framework: wordpress
  site: wjct
  id: xxxx
```
`pantheon.upstream.yml'
```yml
api_version: 1
php_version: 7.3
```

**Tell us about the command you were running**

```bash
lando pull -c=none -d=live -f=none
```
**Tell us about the error you got**

```bash
Access confirmed!
Certificate will not expire
Cert is good!
Validating you can pull the database from live...
 ----------------- ---------------------------
  ID                live
  Created           2017-07-24 19:09:02
  Domain            live-wjct.pantheonsite.io
  Locked            false
  Initialized       true
  Connection Mode   git
  PHP Version       7.0
 ----------------- ---------------------------
Confirmed!
Destroying all current tables in database if needed...
Dropping WJCT-Test1 table from lando database...
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-Test1' at line 1
```

**Tell us generally about your bug**
I'm unable to pull my DB. I was able to pull it before. 
I tried a ```lando rebuild,``` that did not fix it. I did a ```lando destroy,``` deleted the .git folder and the .lando.yml file and did a ``lando init`` and it was able to pull the DB once, but the second time I tried to pull it I got the same error message.

**Comment by calumet45** [comment]
I ran into this same situation in my Drupal 7 database. I narrowed it down to a table name having a hyphen in it, for instance your db pull failed on the table named "????-Test" 
I got around my problem with this by renaming the table.
However, I think that the db script may just need to escape the hyphens.

**Comment by pirog** [comment]
This should be fixed in the next release! Thanks for reporting!

**Comment by RayHollister** [comment]
Weird, so I stopped having that issue, but just started having it again today. Ironically I Googled for an answer and found this thread!

**Comment by RayHollister** [comment]
Darn, I updated to 3.1.4 and I'm still having the same issue.
