### ISSUE TITLE
Unable to 'lando pull' pantheon site

### ISSUE THREAD

**Issue by Cuttsy27** [lando/lando#308]
Bug Report
==========

Windows 10 Pro
Lando v3.0.0-beta.7

.lando.yml file includes: 

```
name: pantheon
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: axia-lawyers
  id: ee7f951a-ab6a-477d-9470-48b10c6be74d
```

The site was completely functional before a Docker update. Updated docker and site wasn't working, so I've created a new folder and am pulling the site fresh from Pantheon to build from there.

Process:
1. lando init pantheon
2. lando start
3. lando pull (pull code, db and files) and following error is given.

```
fatal: Not a git repository (or any parent up to mount point /app)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Verifying that you are logged in and authenticated by getting info about axia-lawyers...
Zend OPcache requires Zend Engine API version 320151012.
The Zend Engine API version 320160303 which is installed, is newer.
Contact Zend Technologies at http://www.zend.com/ for a later version of Zend OPcache.

Xdebug requires Zend Engine API version 320151012.
The Zend Engine API version 320160303 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/bcmath.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/bcmath.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/bz2.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/bz2.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/calendar.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/calendar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/gd.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/gd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/imagick.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/imap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/imap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/ldap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mysqli.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/oauth.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/oauth.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/redis.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/soap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20160303/zip.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20160303/zip.so: cannot open shared object file: No such file or directory in Unknown on line 0
 [error]  You are not logged in. Run `auth:login` to authenticate or `help auth:login` for more info.
error:  Error: 1
    at ChildProcess.<anonymous> (C:\snapshot\cli\lib\shell.js:143:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (C:\snapshot\cli\lib\shell.js:93:10)
    at Object.exports.sh (C:\snapshot\cli\lib\shell.js:209:12)
    at shCompose (C:\snapshot\cli\lib\compose.js:24:16)
    at Object.exports.run (C:\snapshot\cli\lib\compose.js:343:10)
    at C:\snapshot\cli\lib\docker.js:161:22
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\docker.js:148:18)
    at C:\snapshot\cli\lib\engine.js:526:19
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\engine.js:525:4)
    at C:\snapshot\cli\plugins\lando-tooling\lib\tooling.js:106:31
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at C:\snapshot\cli\plugins\lando-tooling\lib\tooling.js:105:10
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-tooling\lib\tooling.js:59:8)
    at C:\snapshot\cli\lib\tasks.js:137:19
    at <anonymous>
```

I'm not sure why this is happening now when it did not happen previously.

**Comment by Cuttsy27** [comment]
This seem to have been resolved by:

1. Create new empty folder
2. cd into folder
3. lando init site-slug pantheon (instead of just lando init pantheon)

This downloaded the correct files from pantheon without error.

**Comment by pirog** [comment]
@Cuttsy27 id encourage you to update to beta.10+ as there was a change in the syntax of the `lando init` command which i'm guessing is responsible for your issue. 

That said, i think you could alternatively just login via terminus before you do the pull since that seems to be the error you are getting `lando terminus auth:login --machine-token=mytoken`

**Comment by ownsourcing** [comment]
I'm getting the same issue. Followed notes about auth posted by @pirog and error persists: 'fatal: Not a git'.

MacOS 10.12.6
Lando updated to v3.0.0-beta.24 (same issue on whatever earlier version I had)

**Comment by davisshaver** [comment]
@pirog I just wanted to clarify expected behavior here... After updating Lando and re-installing site, I had to authenticate terminus within the container again.

Should we have to authenticate in the Lando environment or is there a step I'm missing?

**Comment by pirog** [comment]
AFAIK that is the expect d behavior

**Comment by ccharlton** [comment]
This worked for me: `lando terminus auth:login --machine-token=ABCDEFGHIJKLMNOPQRSTUVQXYZ` (don't steal my unique machine token)

**Comment by pirog** [comment]
!http://ridgeroadmedia.net/wp-content/uploads/2017/03/12345.jpg

**Comment by logancalldev** [comment]
Looks like I'm getting the same error. `fatal: Not a git repository (or any parent up to mount point /app)`

Current version: `v3.0.0-beta.35`

Anytime I run `lando terminus....` it says it doesn't recognize the terminus argument. However, I have authenticated by doing this -> `lando init`, then selected `pantheon`, then selected `add a different token`. Then I was able to enter a token from pantheon. As such, i'm guessing this isn't the issue for me.

After I select the site I run `lando start` and then `lando pull` to get the code, db, files. Then that error shows up. I was using an older version of lando (from `brew cask install lando`), but i've since properly uninstalled it and installed the latest version from the website. I've generated a new token via the method explained above. I've been at this for a while now and am unsure where to go next. Any ideas?

**Comment by pirog** [comment]
@logancalldev `lando init` is not going to git clone your codebase so the error you are getting makes sense. You'll want to either `git clone && lando init` or `lando init pantheon` before you do the `lando pull`. 

Pretty sure this is in the docs ;)

**Comment by logancalldev** [comment]
@pirog Thanks for the quick response. The process I've been following > `lando init` > (select pantheon) > (select pantheon site) > `lando start` > `lando pull`. Is that not the same process you're describing?

**Comment by pirog** [comment]
it is not. i would check out https://docs.devwithlando.io/started.html which explains teh difference between `lando init` and `lando init <method>`

**Comment by logancalldev** [comment]
Ah! That makes sense, sorry for missing that. Thanks @pirog

**Comment by jlandrum** [comment]
@smthomas 

I just started getting the same behavior - wasn't happening last week. Should a ticket be opened perhaps?

**Comment by smthomas** [comment]
@jlandrum That would probably be a good idea as I think it's a separate issue (although it is similar to this one). The next time I run into the issue in my local dev I can create a new issue with documentation/details. However, if you can reproduce it easily, feel free to report it.

**Comment by smthomas** [comment]
@jlandrum I submitted a new issue for this at https://github.com/lando/lando/issues/1284
