### ISSUE TITLE
Docker mysql:latest has updated to 8.x and crashes database containers.

### ISSUE THREAD

**Issue by sk33lz** [lando/lando#908]
Bug Report
==========
# Setup
OS: Mac 10.13.4
Docker: 18.03.0-ce-mac60
Lando: v3.0.0-beta.40

# Problem
Running `lando start` on a new project ends up in a loop waiting for the database service to start. Running `lando destroy` and `lando rebuild` does not resolve the issue.

Rebuilding an existing Lando app on a previous version Lando (v3.0.0-beta.39) or installing Lando v3.0.0-beta.40 causes the mysql:latest docker tag to install MySQL 8.x. This causes lando mysql containers to fail to start with a repeating loop of the following message:

`Waiting until database service is ready...`

I did a `docker ps -a` to figure out what the container ID was for the mysql database container and ran `docker start $CONTAINERID -a` to see what the issue was. I ended up with a bunch of errors during the mysqld startup process at the docker-entrypoint.sh step.

```
Running command docker-entrypoint.sh mysqld
2018-04-20T19:56:07.344153Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
2018-04-20T19:56:07.344245Z 0 [Warning] [MY-011068] [Server] The syntax 'expire-logs-days' is deprecated and will be removed in a future release. Please use binlog_expire_logs_seconds instead.
2018-04-20T19:56:07.344359Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.11) starting as process 103
Reading package lists...mbind: Operation not permitted
mbind: Operation not permitted
mysqld: Table 'mysql.plugin' doesn't exist...
```

The error continues on until mysqld shuts itself down.

I noticed in the output that `mysql Ver 8.0.11` was installed. It turns out that the docker:latest tag was updated yesterday from 5.x to 8.x. See https://github.com/docker-library/mysql/commit/ff627942605ce08a32fa527993337df0e9856760.

# Workaround
I was able to workaround this issue for now by adding database service with `mysql:5.7` defined.

```
services:
  database:
    type: mysql:5.7
```

# Proposed Solution
I feel that given the `mysql:latest` docker tag can change at any time, perhaps Lando should pin a specific mysql version as the default mysql version based on the current Debian release, or something clever so that the mysql version can't change behind the scenes.

**Comment by cboyden** [comment]
I just started evaluating Lando today, and I can confirm both the problem and the workaround. The proposed solution sounds fine to me.

**Comment by gugerard** [comment]
Same here, thanks for the workaround.

**Comment by stefanospetrakis** [comment]
+1 many thanks for reporting this promptly and clearly!

**Comment by legovaer** [comment]
I'm actually using the workaround but when I do a lando rebuild I get an endless list of this:

**Comment by dustinleblanc** [comment]
@legovaer NICE!

You can probably destroy and then start if you have some cruft from the old database settings around. I intend to push a fix for this issue shortly

**Comment by uberhacker** [comment]
I'm having this issue on ANY version of MySQL including 5.7 running beta.39.

**Comment by legovaer** [comment]
@dustinleblanc I tried:

```
$ lando destroy
? Are you sure you want to DESTROY? Yes
Stopping tqfsd_nginx_1     ... done
Stopping tqfsd_cache_1     ... done
Stopping tqfsd_database_1  ... done
Stopping tqfsd_pma_1       ... done
Stopping tqfsd_appserver_1 ... done
Stopping tqfsd_mailhog_1   ... done
Removing tqfsd_nginx_1     ... done
Removing tqfsd_cache_1     ... done
Removing tqfsd_database_1  ... done
Removing tqfsd_pma_1       ... done
Removing tqfsd_appserver_1 ... done
Removing tqfsd_mailhog_1   ... done
Removing network tqfsd_default
Removing volume tqfsd_data
Removing volume tqfsd_appserver
Removing volume tqfsd_data_database
```

Then:

```
$ lando start
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "tqfsd_default" with the default driver
Creating volume "tqfsd_data" with default driver
Creating volume "tqfsd_appserver" with default driver
Creating volume "tqfsd_data_database" with default driver
Creating tqfsd_pma_1       ... done
Creating tqfsd_database_1  ... done
Creating tqfsd_cache_1     ... done
Creating tqfsd_mailhog_1   ... done
Creating tqfsd_appserver_1 ... done
Creating tqfsd_nginx_1     ... done
Waiting until nginx service is ready...
Waiting until appserver service is ready...
Waiting until mailhog service is ready...
Waiting until database service is ready...
Waiting until pma service is ready...
Waiting until cache service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...
Waiting until database service is ready...
Waiting until nginx service is ready...

```

I'm using 3.0.0-beta.40

**Comment by dustinleblanc** [comment]
I mean, you will see those until it finishes startup or timesout, so I don't see an issue specifically there

**Comment by uberhacker** [comment]
I have confirmed the proposed solution works on ANY MySQL version, not just the latest:
```
services:
  database:
    type: mysql:#.#
```
I guess the fix would/should be the config below either needs removed or updated so the services -> database section is not needed.
```
config:
  mysql: #.#
```

**Comment by jacine** [comment]
Is there a workaround for the Pantheon recipe?  None of the above has worked for me. Thanks!

**Comment by dustinleblanc** [comment]
@jacine Mariadb is not affected by this issue, if a Pantheon recipe isn't booting, you probably have a different issue

**Comment by jacine** [comment]
Thank you @dustinleblanc! I wasn't sure, but this seemed like the best lead, after reading through the issues here, and trying a bunch of different things (including completely reinstalling Lando, Docker, and all config). My problem is actually with `lando pull`, which fails to import the DB with an SQL syntax error. Lando does boot and run properly, so I should probably open a separate issue.  Thanks! 😄

**Comment by dustinleblanc** [comment]
@jacine No problem 👍 

We did have an issue on the platform the other day that was a mistake that was causing syntax errors like this on lando pulls. It was related to a patch we released the previous day, it got fixed yesterday though. Are things behaving normally for you now?

**Comment by nanophp** [comment]
8.0.15 still fail and waiting for the build. MySQL 5.7 totally work but I wanna upgrade MySQL version, anyone fixes the issue?

**Comment by pjoulot** [comment]
Ok just found a workaround, use a custom config for the database

In your .lando.yml

```
config:
  config:
    database: config/custom-mysql.conf
```

And put inside the custom-mysql.conf file:

```
[mysqld]
default_authentication_plugin=mysql_native_password
```
