### ISSUE TITLE
Lando suddenly missing drush tooling for Pantheon sites

### ISSUE THREAD

**Issue by skye-va** [lando/lando#931]
Bug Report
==========

**Tell us about your setup**
lando beta42

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: james-birrell-design-lab
recipe: pantheon
config:
  framework: drupal8
  site: james-birrell-design-lab
  id: b396e796-b07f-4601-9908-bc38250b761b
 ```

pantheon.upstream.yml
```yml
# IMPORTANT NOTE:
# Do not edit this file unless you are doing so in your custom upstream repository.
# Override the defaults specified here in a site-specific `pantheon.yml` file.
# For more information see: https://pantheon.io/docs/pantheon-upstream-yml
api_version: 1
php_version: 7.0
```

**Tell us about the command you were running**

```
lando drush status
```

**Tell us about the error you got**

```bash
info: Bootstraping...
info: Configuring app plugin
info: Configuring engine plugin
info: Configuring proxy plugin
info: Initializing proxy plugin
info: Configuring services plugin
info: Initializing app plugin
info: Initializing engine plugin
info: Initializing events
info: Initializing init framework
info: Initializing recipes plugin
info: Initializing services
info: Initializing tooling plugin
info: Initializing core plugin
info: Configuring networking plugin
info: Bootstrap completed.
info: Initializing cli
info: App jamesbirrelldesignlab is ready!
The Drush launcher could not find a local Drush in your Drupal site.
Please add Drush with Composer to your project.
Run 'cd "/app" && composer require drush/drush'
```

**Tell us generally about your bug**

Since upgrading to beta.41 all my Pantheon sites are suddenly missing drush.
As a temporary workaround, I tried the above, but when I ssh into my lando app, I get this error:

```
composer require drush/drush
    1/1:	http://packagist.org/p/provider-latest$2a64cebc8ca77e1f3031bae1bde7b2a2bd1299bec89b5804ef360d745743c059.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Using version ^9.2 for drush/drush
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/cache v1.7.1 requires php ~7.1 -> your PHP version (7.0.30) does not satisfy that requirement.
    - doctrine/cache v1.7.1 requires php ~7.1 -> your PHP version (7.0.30) does not satisfy that requirement.
    - Installation request for doctrine/cache (locked at v1.7.1) -> satisfiable by doctrine/cache[v1.7.1].
```

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. Started up lando site in terminal window
2. Ran any drush command, e.g. lando drush status
```

**Tell us more**

Does this bug prevent you from using lando?
Not lando, but Drush is important!!!

**Comment by jproctor** [comment]
`lando rebuild` fixed this for me.

**Comment by skye-va** [comment]
Unfortunately not for me. Destroyed lando and Docker and completely re-installed, but I still get ```/bin/sh: 1: drush: not found``` in response to any ```lando drush``` command

**Comment by serhatozkara** [comment]
I have the same issue. In the last couple of weeks, I had all sorts of problems with Lando.

**Comment by shaal** [comment]
I had this issue as well (Ubuntu 18.04, Lando Beta44), using Pantheon + D7 & D8.
What eventually solved it for me (might have been an overkill, but it worked :) -

1. Uninstall Lando Beta44
2. Destroy all images, containers, volumes
(followed instructions here https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes)
3. Deleting `~/.lando` directory
4. Install Lando Beta44

And now `lando drush` works!

**Comment by serhatozkara** [comment]
`lando rebuild appserver` did the trick for me.

**Comment by shaal** [comment]
Actually... I have now D8 Pantheon that wouldn't let me run drush
```/bin/sh: 1: drush: not found```

after running `lando rebuild` I get this output + error 
```? Are you sure you want to rebuild? Yes
Killing spiewak_edge_ssl_1  ... done
Killing spiewak_edge_1      ... done
Killing spiewak_nginx_1     ... done
Killing spiewak_appserver_1 ... done
Killing spiewak_database_1  ... done
Killing spiewak_index_1     ... done
Killing spiewak_cache_1     ... done
Removing spiewak_edge_ssl_1  ... done
Removing spiewak_edge_1      ... done
Removing spiewak_nginx_1     ... done
Removing spiewak_appserver_1 ... done
Removing spiewak_database_1  ... done
Removing spiewak_index_1     ... done
Removing spiewak_cache_1     ... done
Pulling database (mariadb:10.0)...
Pulling cache (redis:2.8)...
Pulling index (devwithlando/pantheon-index:3.6-3)...
Pulling appserver (devwithlando/pantheon-appserver:7.1)...
Pulling nginx (nginx:1.8)...
Pulling edge (eeacms/varnish:4.1-3.0)...
Pulling edge_ssl (nginx:1.13)...
database uses an image, skipping
cache uses an image, skipping
index uses an image, skipping
appserver uses an image, skipping
nginx uses an image, skipping
edge uses an image, skipping
edge_ssl uses an image, skipping
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating spiewak_cache_1    ... done
Creating spiewak_index_1    ... done
Creating spiewak_database_1 ... done
Creating spiewak_appserver_1 ... done
Creating spiewak_nginx_1     ... done
Creating spiewak_edge_1      ... done
Creating spiewak_edge_ssl_1  ... done
Waiting until edge_ssl service is ready...
Waiting until edge service is ready...
Waiting until nginx service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until index service is ready...
Waiting until cache service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Waiting until edge_ssl service is ready...
Pantheon pre-run scripting
Setting up client key /lando/keys/pantheon/spiewak/cert.pem
Changed current directory to /var/www/.composer

                                                                                
  [ErrorException]                                                              
  file_put_contents(./composer.json): failed to open stream: Permission denied  
                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

error: Looks like one of your build steps failed...
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME           spiewak                                                  
 LOCATION       /home/shaal/code/lando/spiewak                           
 SERVICES       appserver, nginx, database, cache, edge_ssl, edge, index 
 NGINX URLS     https://localhost:32843                                  
                http://localhost:32844                                   
 EDGE URLS      http://localhost:32842                                   
                http://spiewak.lndo.site                                 
                https://spiewak.lndo.site                                
 EDGE_SSL URLS  https://localhost:32841                                  ```

and drush would still not be found.

But running `lando restart` did the job!
```...
debug: Retrieved from memcache with key engineup
verbose: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
Pantheon pre-run scripting
Setting up client key /lando/keys/pantheon/spiewak/cert.pem
Changed current directory to /var/www/.composer
Using version ^0.3.7 for hirak/prestissimo
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing hirak/prestissimo (0.3.7): Downloading (100%)         
Writing lock file
Generating autoload files
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0    919      0 --:--:-- --:--:-- --:--:--   918
100  303k  100  303k    0     0   265k      0  0:00:01  0:00:01 --:--:--  265k
Drush Launcher Version: 0.6.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  713k  100  713k    0     0   545k      0  0:00:01  0:00:01 --:--:--  544k
 [notice] Logging in via machine token.
...```
and now `lando drush` is working again!

**Comment by xaqrox** [comment]
I am also having this problem. Restarting/rebuilding seems to fix it for a while, but eventually drush goes away again...

**Comment by xaqrox** [comment]
Extra wrinkle: `lando drush` works in the root directory of my project, and any other directory, except `web` and its children.

**Comment by JackSoby** [comment]
Had the same issue. Had to globally reinstall Drush.

**Comment by dustinleblanc** [comment]
I am going to call this likely fixed by bbbf554ebbb40397a3c9b6f59db7791fb3f18de3 and 0b21825c7a8836700753ed3bdf9618577e5adcbe

Prestissimo will be installed in the image and drush will be installed Globally as of next release

**Comment by ckng** [comment]
Still getting the same problem. This is after `lando rebuild`. This was working before beta.47.

```
$ lando version
v3.0.0-beta.47
```

.lando.yml
```
name: themes
recipe: pantheon
config:
  framework: drupal8
  site: themes
  id: 593e3291-2ffa-4e78-a51f-6c77f3066912
```

pantheon.upstream.yml
```
api_version: 1
php_version: 7.0
```

**Tell us about the command you were running**
```
$ lando drush --verbose -vvvv
```

**Tell us about the error you got**
```
/bin/sh: 1: drush: not found
```

Drush is installed to the site.
"drush/drush": "^8.1",

**Comment by ckng** [comment]
Tested v3.0.0-beta.47 with a new site, `lando pull` failed with the following. Unsure if they are related, files push and pull are broken too.

```
...
Downloading drush aliases...
 [notice] Aliases file written to ~/.drush/pantheon.aliases.drushrc.php.
/helpers/pull.sh: line 137: drush: command not found
 [notice] OK >> dev-endless-themes.pantheonsite.io responded
Pulling database from dev...
...
1526439041_backup_files
Pulling files from dev...
receiving incremental file list
rsync: mkdir "/app/sites/default/files" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]

Pull complete!
```

File push error
```
...
Pushing files to dev...
sending incremental file list
rsync: change_dir "/app/sites/default/files" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  9.14 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
```

**Comment by DanLaufer** [comment]
`lando rebuild` fixed for me, as well.

**Comment by alphex** [comment]
just adding to the pile.

lando version == v3.0.0-beta.47

A fresh site, with any `lando drush` command resulting in

    lando drush uli
    /bin/sh: 1: drush: not found

`lando rebuild` solved it, but, spit out a bunch of errors like this

    `ERROR: for cache  Get https://registry-1.docker.io/v2/library/redis/manifests/2.8: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fredis%3Apull&service=registry.docker.io: unexpected EOF` which I'll open another ticket about (if I can't find an existing one)

Thank you

**Comment by philoSurfer** [comment]
`lando rebuild` should fix this every time. 

Why does it happen?  that is the question that needs to be answered.   I suspect it is due to a docker update but cannot confirm ( I recently updated docker outside of Lando's RC-1 candidate for performance gains)

**Comment by carnnia** [comment]
lando rebuild has not worked for me.
>$ docker version
Client:
 Version:           18.09.0
 API version:       1.39
>$ lando version
v3.0.0-rc.1
>lando drush
/bin/sh: 1: drush: not found
>$ lando drupal
/bin/sh: 1: drupal: not found

**Comment by danieledwins** [comment]
I get this error at work, but not at home. Our work firewall is blocking pulling the database due to a malware threat – perhaps because the database is coming from a Google server that has been used maliciously. If rebuild doesn't solve your issue, check your firewall.

**Comment by jasonglisson** [comment]
Anyone have a fix for this? Just got a docker update a day ago and now this happens every time I run a drush command. I was just about to do some module updates and core Drupal updates.....and kinda need Drush.

**Comment by dustinleblanc** [comment]
@jasonglisson if you're having problems with drush not being found in the container, check the output of a startup or rebuild command and look for errors in build steps. They can often cause our later build steps that update the path to include Drush to not run.
